* Todo app using just React with POJS - no JSX or ES6
  :PROPERTIES:
  :CUSTOM_ID: todo-app-using-just-react-with-pojs---no-jsx-or-es6
  :END:

- published date: 2016-12-03 09:56
- keywords: ["brian-holt", "frontend-masters", "javascript", "learning", "react", "todoapp"]
- source: https://github.com/tamouse/todo-react-nojsx

I just moderated the [[https://frontendmasters.com][Frontend Masters]] class "Complete Introduction to React" taught by [[https://twitter.com/holtbt][Brian Holt]] of Netflix and Reddit fame.

It was a great course, but as moderator I was doing a lot of things to keep the chat room flowing and didn't get to pay much attention to the detail Brian was presenting, and definitely didn't have time in class to try out stuff.

So I thought I'd just give the first bit of Brian's presentation a go, where we just worked with React as a plain JS library, nothing fancy, no JSX transpiling, etc.

[[https://github.com/tamouse/todo-react-nojsx][This]] is the result, the canonical single page Todo application.

It was pretty easy, and pretty fun. I kept only to the [[https://facebook.github.io/react/docs/][React docs]], especially

- [[https://facebook.github.io/react/docs/react-without-es6.html][React Without ES6 - React]]
- [[https://facebook.github.io/react/docs/react-without-jsx.html][React Without JSX - React]]

I'm pleased with the experiement.
