* How do I get to the command line on a Mac?

- Time-stamp: <2018-11-06 09:31:47 tamara>
- published date: 2018-07


** From Finder
   :PROPERTIES:
   :CUSTOM_ID: from-finder
   :END:

1. Open a Finder window.

2. Go to the =Applications= folder (this could be in the side bar of the Finder window or you should be able to press Shift-Command-A unless you've previously modified your keyboard shortcuts.)

3. Scroll down to the =Utilites= folder and double click it to open it.

4. Scroll down until to find the =Terminal= application, and double click it to open it.

5. When it opens, the icon for =Terminal= will appear in the Dock. Right-click the icon, and select the "Keep in Doc" option.

Now you can easily open the Terminal just by clicking on the icon in the Dock when you want one.

** From Spotlight
   :PROPERTIES:
   :CUSTOM_ID: from-spotlight
   :END:

1. Press Command-Spacebar to open the Spotlight search dialog.

2. Type "ter" -- this should be enough to highlight the =Terminal= application.

3. Press the Return key and =Terminal= will start.

Follow step 5 in the previous section to keep Terminal in your Dock.
