* A place to get started in web design
  :PROPERTIES:
  :CUSTOM_ID: a-place-to-get-started-in-web-design
  :END:

- published date: 2014-07-05 10:57:18 -0500
- keywords: ["beginners", "classes", "frontend-masters", "learning", "swaac", "web-design"]
- source:
- redirect_from: ["/blog/2014/07/05/a-place-to-get-started-in-web-design/"]

I'm forwarding (from an e-mail) an opportunity to attend a workshop for folks who are at the very beginning of learning web design, or are asking the quesiton "Where do I begin?".

I recently attended a Front End Masters event, and it was the sort of thing I enjoy: informal, lots of interaction, great workshop leaders, people with something to say.

[[https://frontendmasters.com/workshops/introduction-web-development/][Event info]]

[[https://mjg.wufoo.com/forms/introduction-to-web-development-giveaway/][Scholarship info]]

Click though the cut to see about the workshop.

#+BEGIN_HTML
  <!--more-->
#+END_HTML

#+BEGIN_QUOTE
  Hey Tamara,

  Most of our courses and workshops have targeted intermediate to advanced developers, but we still get asked often, "Where do I even get started with web development? There are so many topics to learn!" Before today we didn't really have an answer to this. But now we do!

  We're excited to announce a new, 2-day introduction to web development workshop. We even have scholarships available for those who cannot afford to attend.

  - Nina Zakharenko
  - Brian Holt

  Come join Brian Holt and Nina Zakharenko (developers at Reddit.com) to learn the fundamentals of web development.

  Learn how to craft your ideas into something real! Coding is the ability to take the abstract and make it concrete. In this class we'll show you how to go from no prior coding knowledge to crafting your own websites using HTML, CSS, JavaScript, and node.js. * Discover the basics of how web browsers work.. * Discover how to write solid HTML.. * Discover how to style your content to reflect your vision using CSS.. * Discover the basics of programming which apply in language.. * Discover how to write JavaScript for the browser.. * Discover the basics of using the command-line.. * Discover how to code JavaScript for the server using node.js and Express..

  Here are the links again:

  Event info --> https://frontendmasters.com/workshops/introduction-web-development/

  Register for scholarship / free entry --> https://mjg.wufoo.com/forms/introduction-to-web-development-giveaway/

  Please spread word about this event to anyone who wants to get started!

  --\\
  Marc Grabanski\\
  President & UI/UX Developer\\
  Frontend Masters

  Copyright © 2014 MJG International (Publisher of Frontend Masters), All rights reserved.

  Our mailing address is:\\
  MJG International (Publisher of Frontend Masters)\\
  3977 Egan Drive\\
  Savage, MN 55378
#+END_QUOTE
