* Dieter Ram's 10 Principles For Good Design - readymag
  :PROPERTIES:
  :CUSTOM_ID: dieter-rams-10-principles-for-good-design---readymag
  :END:

- published date: 2014-02-04 11:48
- keywords: ["design", "dieter-rams", "swaac", "vitsoe"]
- source:
- redirect_from: ["/blog/2014/02/04/dieter-rams-10-principles-for-good-design-readymag/"]

Back in the late 1970s, Dieter Rams was becoming increasingly concerned by the state of the world around him --- "an impenetrable confusion of forms, colours and noises." Aware that he was a significant contributor to that world, he asked himself an important question: is my design good design?

As good design cannot be measured in a finite way he set about expressing the ten most important principles for what he considered was good design. Sometimes they are referred as the /"Ten commandments"/. Here they are.

#+BEGIN_HTML
  <!--more-->
#+END_HTML

Material from [[https://www.vitsoe.com/][Vitsœ]].

** 1 Good design is innovative
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-innovative
   :END:

The possibilities for innovation are not, by any means, exhausted. Technological development is always offering new opportunities for innovative design. But innovative design always develops in tandem with innovative technology, and can never be an end in itself.

** 2 Good design makes a product useful
   :PROPERTIES:
   :CUSTOM_ID: good-design-makes-a-product-useful
   :END:

A product is bought to be used. It has to satisfy certain criteria, not only functional, but also psychological and aesthetic. Good design emphasises the usefulness of a product whilst disregarding anything that could possibly detract from it.

** 3 Good design is aesthetic
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-aesthetic
   :END:

The aesthetic quality of a product is integral to its usefulness because products we use every day affect our person and our well-being. But only well-executed objects can be beautiful.

** 4 Good design makes a product understandable
   :PROPERTIES:
   :CUSTOM_ID: good-design-makes-a-product-understandable
   :END:

It clarifies the product's structure. Better still, it can make the product talk. At best, it is self-explanatory.

** 5 Good design is unobtrusive
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-unobtrusive
   :END:

Products fulfilling a purpose are like tools. They are neither decorative objects nor works of art. Their design should therefore be both neutral and restrained, to leave room for the user's self-expression.

** 6 Good design is honest
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-honest
   :END:

It does not make a product more innovative, powerful or valuable than it really is. It does not attempt to manipulate the consumer with promises that cannot be kept.

** 7 Good design is long-lasting
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-long-lasting
   :END:

It avoids being fashionable and therefore never appears antiquated. Unlike fashionable design, it lasts many years --- even in today's throwaway society.

** 8 Good design is thorough down to the last detail
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-thorough-down-to-the-last-detail
   :END:

Nothing must be arbitrary or left to chance. Care and accuracy in the design process show respect towards the user.

** 9 Good design is environmentally-friendly
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-environmentally-friendly
   :END:

Design makes an important contribution to the preservation of the environment. It conserves resources and minimises physical and visual pollution throughout the lifecycle of the product.

** 10 Good design is little design as possible
   :PROPERTIES:
   :CUSTOM_ID: good-design-is-little-design-as-possible
   :END:

Less, but better -- because it concentrates on the essential aspects, and the products are not burdened with non-essentials.

* Back to purity, back to simplicity.
  :PROPERTIES:
  :CUSTOM_ID: back-to-purity-back-to-simplicity.
  :END:

Dieter Rams

Industrial designer (b1932)

Dieter Rams was born in Wiesbaden, Germany, in 1932. He was strongly influenced by the presence of his grandfather who was a carpenter. Rams's early awards for carpentry led to him training as an architect as Germany was rebuilt in the early 1950s.

Prompted by an eagle-eyed friend, Rams applied for a job at the German electrical products company, Braun, in 1955. He was recruited by Erwin and Artur Braun following the death of their father and his job was to modernise the interiors of the company that was launching revolutionary electrical products.

Rams became a protégé of the Ulm School of Design (successor to the Bauhaus) luminaries Hans Gugelot, Fritz Eichler and Otl Aicher.

He quickly became involved in product design --- famously adding the clear perspex lid to the SK4 radiogram in 1956 --- and was appointed head of design at Braun from 1961 to 1995.

Together with his design team, he was responsible for many of the seminal domestic electrical products --- and some furniture --- of the 20th century.
