* Bootstrap Follies: Vertically and Horizontally Centered Form
  :PROPERTIES:
  :CREATED_ON: 2013-08-11T09:59
  :KEYWORDS:     layout, web design, bootstrap, css, centering
  :UPDATED_ON: [2018-09-02 Sun 22:18]
  :END:

/Note: updated to 3.3.7/

[[http://getbootstrap.com/3.3.7/][Bootstrap]] provides a really nice framework and set of components to make a very nice looking web page out of the box. However, it's not always clear how to do something. A frequently asked question among CSS newbies is:

** How do I center a form on my window?

This is a pretty-well solved problem /outside/ of bootstrap, and you could use the same method inside bootstrap as well.

There are some compromises, though:

1. You have to decide on the height and width of the box your form will take.
2. You have to go through a lot to get it to look "bootstrap-ish".

I'll go through the method so you can understand what is going on.

** Pure (?) CSS implementation

In a local style sheet, define a class for your centered form. I'm
calling mine 'centered-box', and determine the box will be 600px wide by
300px high.

[[https://codepen.io/tamouse/pen/NLpVjq?editors=0100][Bootstrap Follies: Centering a Login Form on Codepen.io]]

#+BEGIN_EXPORT html
<p data-height="265" data-theme-id="0" data-slug-hash="NLpVjq" data-default-tab="html,result" data-user="tamouse" data-pen-title="Bootstrap Follies: Centering a Login Form" class="codepen">See the Pen <a href="https://codepen.io/tamouse/pen/NLpVjq/">Bootstrap Follies: Centering a Login Form</a> by Tamara Temple (<a href="https://codepen.io/tamouse">@tamouse</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>
#+END_EXPORT

** The Bootstrap Static Modal

Bootstrap provides a component, =modal=, that basically does the same
thing as above, although it makes an additional compromise that i cannot
/a priori/ know the height of the box, so simply sets the top value to
10%. To use modal, simply make it the class on your box, and omit the
styling from the previous example.

[[https://codepen.io/tamouse/pen/wEJbxK?editors=1000][Bootstrap Follies: Using a modal for a Login Form on Codepen.io]]

#+BEGIN_EXPORT html
<p data-height="265" data-theme-id="0" data-slug-hash="wEJbxK" data-default-tab="html,result" data-user="tamouse" data-pen-title="Bootstrap Follies: Using a modal for a Login Form" class="codepen">See the Pen <a href="https://codepen.io/tamouse/pen/wEJbxK/">Bootstrap Follies: Using a modal for a Login Form</a> by Tamara Temple (<a href="https://codepen.io/tamouse">@tamouse</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>
#+END_EXPORT

The major problem with using a modal in bootstrap is it has to be triggered by something. The example above shows the modal being triggered by clicking on the button. You can trigger it with javascript as well.

After working with bootstrap modals and panels, I've changed my mind: originally I said I prefer the modal version, but I think it requires too much on the part of the coder to trigger the modal, when likely all you want on a login page is the login form.

Leave modals for asking the user questions or having them update things in the normal stream of events, and not for the sole use on a page.
