Regular Expressions (commonly referred to as 'regexes') can be highly
opaque voodunesque constructions that often are difficult to decipher
and thus modify when the time comes. Regexes seem to be a black art to
many people, and something that takes a while to understand and master.
Documenting regexes is something practically no one does, yet could be
so helpful for many people.

** PCRE modifiers
   :PROPERTIES:
   :CUSTOM_ID: pcre-modifiers
   :END:

[[http://pcre.org][PCRE]] (Perl Compatible Regular Expressions) has
several modifiers that do various things to the action of the regex.
These are the ones defined for PCRE:

- *i:* make the match case insensitive
- *m:* multiline
- *s:* dot matches newlines
- *x:* ignore white spaces in specification

** Enter the *x* modifier
   :PROPERTIES:
   :CUSTOM_ID: enter-the-x-modifier
   :END:

The *x* modifier is where we can take advantage of the regex ignoring
white space between pattern elements to beautify the regex and insert
comments.

{% highlight perl %} $is_blank_re = qr{^\s*$}; {% endhighlight %}

The above regex is quite simple, most people should understand it well
enough. But for illustration, let's break this up a bit, beautify it,
and add some comments:

{% highlight perl %} $is\_blank\_re = qr{ \^ # match the beginning of
the string \s*                  # match zero or more white spaces $ #
match the end of the string }x; {% endhighlight %}

This at least makes it clearer what each element of the regex /is/ and
what it /does/. Using the regex defined is the same in either case:

In =perl=:

{% highlight perl %} while ($line = ) { next if (
$line =~ m{$is\_blank\_re} ); # process the line } {% endhighlight %}

Similarly, in =ruby=:

{% highlight ruby %} is\_blank = %r{ \^ # matches beginning of line
\s*     # match zero or more white spaces $ # match end of the line }x

STDIN.each\_line do |line| next if line.match is\_blank # ... process
the line end {% endhighlight %}

** Language Implementations
   :PROPERTIES:
   :CUSTOM_ID: language-implementations
   :END:

- [[http://pcre.org][PCRE]]
- [[http://perldoc.perl.org/perlre.html][Perl]]
- [[http://us3.php.net/manual/en/reference.pcre.pattern.modifiers.php][PHP]]
- [[http://ruby-doc.org/core-2.1.4/Regexp.html#class-Regexp-label-Options][Ruby]]
