* About
  :PROPERTIES:
  :CUSTOM_ID: about
  :END:

** Welcome to my SWaaC blog!
   :PROPERTIES:
   :CUSTOM_ID: welcome-to-my-swaac-blog
   :END:

What is SWaaC? Software as a Craft!

I am a firm believer that software development is primarily a craft, that is, it involves skills, knowledge, creativity, problem-solving and critical thinking skill, and a deeply personal desire to make things.

I [[file:%7B%7B%22/swaac/2013/08/03/programmers-creativity/index.html%22%20%7C%20prepend:%20site.baseurl%7D%7D][wrote a post on this]] back in 2013:

#+BEGIN_QUOTE

  #+BEGIN_QUOTE
    I think most people think programming is cold, precise, and mechanical. It's actually creative, perplexing and deeply personal. --- Unknown (from [[http://discordianquotes.com/quote/think-people-thing-programming-cold-precise-mechanical-actually]])
  #+END_QUOTE

  I've said similar words many times. I wish more people understood them.
#+END_QUOTE

#+BEGIN_QUOTE
  What does it mean to be creative? It usually means making something that other's can see as beautiful, or as unique, but also it means applying your mind to making something real that exists only at first in your mind.
#+END_QUOTE

Several of the posts you'll find here were originally in my personal blog and copied over here. I've decided what I really want is a curated set of my writing on SWAAC, so here we are.
