* LINK: CSS Frameworks vs. CSS Grid

- Time-stamp: <2018-11-14 21:04:07 tamara>
- capture date: [2018-11-14 Wed 20:58]
- keywords: CSS, Grid, Frameworkds, Bootstrap, Rachel Andrew, good advice, Smashing Magazine

- Link: [[https://www.smashingmagazine.com/2018/11/css-frameworks-css-grid/]]

** Quick Summary

#+BEGIN_QUOTE
Have you ever considered whether CSS Grid can actually replace the need for CSS frameworks or third-party component libraries? In doing so, Rachel Andrew discovered a range of reasons people use a third-party framework and the positive and negative things about doing so.
#+END_QUOTE

** Thoughts

I love reading [[https://www.smashingmagazine.com/author/rachel-andrew][Rachel Andrew]]'s posts, everywhere, not just on SmashingMagazine. This one is no different. Rachel is no hardline "you have to use my stuff" writer, she's thoughtfully laid out good reasons for using a CSS framework like Bootstrap, and even given other people's answers as to why it's a good choice. She's also given reasons for *not* using a framework, and why that's a good choice.

Her conclusion, for those coming down on the side of "no framework" are some pretty good steps, and even might help you decide if it's worth going your own way.
