* Link: The Traits of a Proficient Programmer: Gregory Brown
  :PROPERTIES:
  :CUSTOM_ID: link-the-traits-of-a-proficient-programmer-gregory-brown
  :END:

- published date: 2016-07-23 23:15
- keywords: ["gregory-brown", "learning", "link", "oreilly", "proficiency", "programming"]
- source:
- link: {"href"=>"https://www.oreilly.com/ideas/the-traits-of-a-proficient-programmer?imm_mid=0e6043&cmp=em-prog-na-na-newsltr_20160723", "title"=>"The Traits of a Proficient Programmer: Gregory Brown", "date"=>"2016-07-19", "author"=>{"name"=>"Gregory Brown", "url"=>"https://www.oreilly.com/people/9d6b1a5d-34e2-4ec6-9f0a-8cd5041e4313"}}

This article touches on something close to my heart: helping students get beyond the gap between just knowing a bunch of things and acquiring the "mind of the developer" (borrowing a phrase from an anthropologist friend) -- the point at which the person shifts from just collecting knowledge, skills, and facts to having the mind-set of how best to apply them, when not to apply them, know which ones apply, and so on. In another analogy, the jazz musician who knows when to lay out, when to not play the note, how to phrase, and produce jazz, not just strings of notes.

#+BEGIN_QUOTE
  the place where the intermediate programmer tends to get stuck (and many end up stuck there for life) is thinking that the difference between a beginner and an expert can be measured in how much stuff you know. That's only half correct, and it emphasizes the less important half.
#+END_QUOTE

#+BEGIN_QUOTE
  This is where proficiency comes in. And at its essence, proficiency is about "why you do things a certain way"---It's the difference between understanding each of the parts of a problem individually, and understanding how the parts fit into the whole.
#+END_QUOTE

#+BEGIN_QUOTE
  The gap between competence and proficiency may explain why so many people struggle with high level programming ideas
#+END_QUOTE

Not everyone gets there, but I think most who try can eventually get there. I'm still not sure what part we educators play in this, other than give encouragement and provide a rich environment for learning.

Proficiency is learned, I feel, in the doing of something, with the guidance for introspection and reflection.
