* Link: The best coding language for you to learn
  :PROPERTIES:
  :CUSTOM_ID: link-the-best-coding-language-for-you-to-learn
  :END:

- published date: 2014-10-22 00:57
- keywords: ["design-of-solutions", "links", "problem-solving", "roger-huang", "swaac", "think-like-a-programmer"]

A [[http://www.code-love.com/2014/07/22/best-coding-language-learn/?utm_content=buffer53a37&utm_medium=social&utm_source=plus.google.com&utm_campaign=buffer#sthash.XFjxPptN.dpuf][good commentary]] on what language one should /really/ be learning to become a great programmer, from [[http://www.code-love.com/author/roger-huangthoughtbasin-com/][Roger Huang]] on [[http://www.code-love.com/][code(<3)]].

#+BEGIN_QUOTE
  The absolute best thing to learn is to learn how to think like a programmer---learn how to solve problems mathematically, with clean and concise code. Coding languages evolve, they change, they fall in and out of favor. One community might morph into another. The great web applications of the present might be obsolete in a few decades. What won't change is the need for people to think logically, and solve problems---and make it an automated and easier process with machines.
#+END_QUOTE

See more at: [[http://www.code-love.com/2014/07/22/best-coding-language-learn/][http://www.code-love.com/2014/07/22/best-coding-language-learn/]]
