* Beginner Learning section in Pages
  :PROPERTIES:
  :CUSTOM_ID: beginner-learning-section-in-pages
  :END:

- published date: 2016-08-07 09:15
- keywords: ["beginner", "learning"]
- source:

TL;DR: [Beginner Learning Pages][beginner_link]

I am far, far removed from being a beginner at software crafts. I wrote my first BASIC program, a lunar lander game, in 1969, on a cranky old teletype. The program was saved on punched paper tape.

The current age of computers, software development practice, and, probably most importantly, the availability, ubiquity, and democratisation of computers and software development learning materials is so vastly different from 1969. No surprise, I'm not saying anything new. But the implications for me are that it is really hard to re-acquire the mind-set of someone so brand new to programming that they really don't have any sense of how things work with absolutely no reference frames to hang things off of when they set down to learn.

This is frustrating for both of us. I've forgotten what I didn't used to know. You don't know what you need to learn.

{% assign beginner_link = site.baseurl | append: "/pages/learning/beginner/" %}

So I'm starting a new section in the pages of this blog, under [beginner_link] useful. In this section, I want to put together some information for beginners.

They're not going to come in any particular order, for I'm still learning what might be needed. Organization will come, hopefully not too late, and not too poorly.

This section is also going to be very, very Unix, Linux, GNU, and Mac OSX focused, since that's all I really have familiarity with.

Here's a couple I've started off with. I'd really love to hear some feedback on them.

- [[file:%7B%7B%20site.baseurl%20%7D%7D/pages/learning/beginner/how-do-i-get-to-the-command-line-on-a-mac][How do I get to the command line on a Mac?]]
- [[file:%7B%7B%20site.baseurl%7D%7D/pages/learning/beginner/setting-up-your-mac-for-working-on-the-command-line][Setting up your Mac for working on the command line]]

[beginner_link]: {{ "/pages/learning/beginner" | prepend: site.baseurl}} "Beginner Learning Pages"
