* Link: "Learn Enough Command Line To Be Dangerous" by Michael Hartl"
  :PROPERTIES:
  :CUSTOM_ID: link-learn-enough-command-line-to-be-dangerous-by-michael-hartl
  :END:

- published date: 2015-10-12 06:40
- keywords: ["command-line", "link", "programming", "tutorial"]
- source:
- link: {"href"=>"http://www.learnenough.com/command-line-tutorial", "title"=>"Learn Enough Command Line To Be Dangerous", "date"=>"2015", "author"=>{"name"=>"Michael Hartl", "url"=>"mailto:admin@railstutorial.org"}}

[[file:%7B%7Bpage.link.author.url%7D%7D][{{page.link.author.name}}]] has a new tutorial out: [[file:%7B%7Bpage.link.href%7D%7D][{{page.link.title}}]] that will give folks new to development and new to the command line a real leg up in working in the shell.

In the intro, Michael describes computer programming as magic, and I believe that also captures the sense of fun and excitement I have long felt in working with computers:

#+BEGIN_QUOTE
  Computer programming may be as close as we get to magic in the real world: we type incantations into a machine, and---if the incantations are right---the machine does our bidding. To perform such magic, computer witches and wizards rely not only on words, but also on wands, potions, and an ancient tome or two. Taken together, these tricks of the trade are known as software development: computer programming, plus tools like command lines, text editors, and version control. Knowledge of these tools is perhaps the main line between "technical" and "non-technical" people (or, to put it in magical terms, between wizards or witches and Muggles). The present tutorial represents the first step needed to cross this line and learn enough software development to be dangerous---to be able to cast computer spells, and get the machine to do our bidding.
#+END_QUOTE

The web page is free itself. There is an ebook version available to purchase as well.
