* How to reset your Time Capsule to factory settings without losing your data
  :PROPERTIES:
  :CUSTOM_ID: how-to-reset-your-time-capsule-to-factory-settings-without-losing-your-data
  :END:

- published date: 2013-08-28 09:42
- keywords: ["admin", "apple", "technology", "time-capsule", "tutorials"]
- source: http://www.yourdailymac.net/2011/10/how-to-reset-your-time-capsule-to-factory-settings-without-losing-your-data/
- description: A few years back, I was looking for a way to reset my Time Capsule back to it's original factory settings but I didn't want to lose the data that was saved on it. I found this article and it worked well at the time.

- saved_link: http://tt.imageshare.s3.amazonaws.com/clippings/saved_pages/How%20to%20reset%20your%20Time%20Capsule%20to%20factory%20settings%20without%20losing%20your%20data%20%20%20Your%20Daily%20Mac.html

{{ page.description }}

** Summary
   :PROPERTIES:
   :CUSTOM_ID: summary
   :END:

#+BEGIN_QUOTE
  If you are running into problems with your Time Capsule, it may be time to reset your Time Capsule settings to factory settings, without losing the data that is stored on your hard disk.
#+END_QUOTE

#+BEGIN_QUOTE
  But you will first have to try and restart your Time Capsule, this solves in many cases most of the problems, you can restart your Time Capsule by using the AirPort configuration application. When this doesn't solve the problems, you will have to reset the Time Capsule to the default factory settings by performing a hard reset.
#+END_QUOTE

#+BEGIN_QUOTE
  When performing a hard reset, Time Capsule will lose all the settings including authorization access and radius data. The backup data of your system and the name of your Time Capsule will however be safe on your Time Capsule.
#+END_QUOTE

#+BEGIN_QUOTE
  You can reset your Time Capsule by pressing and holding the reset button on your Time Capsule for at least 5 seconds, until the orange LED on the front of your Time Capsule starts to blink. The Time Capsule will automatically restart itself after you let go of the reset button.
#+END_QUOTE
