* Colophon

#+BEGIN_QUOTE
  Colophon \Col"o/phon (k[o^]l"[-o]/f[o^]n), n. [L. colophon finishing stroke, Gr. kolofw`n; cf. L. culmen top, collis hill. Cf. Holm.]

  An inscription, monogram, or cipher, containing the place and date of publication, printer's name, etc., formerly placed on the last page of a book.
#+END_QUOTE

--- from [[http://www.dict.org/bin/Dict?Form=Dict3&Database=gcide][The Collaborative International Dictionary of English v.0.48]] via [[http://www.dict.org/bin/Dict?Form=Dict2&Database=*&Query=colophon][dict.org]]

** Version 4 of my SWAAC blog

In my ever-increasing desire to remove extra steps from my life, and to hopefully increase my frequency of publishing posts on stuff I'm learning (and I *am* learning, *all* the time), I've decided to take a completely different turn, and convert the old [[https://jekyllrb.com][Jekyll]] based blog into one that is *only* posts, written in Emacs' [[https://org-mode.org][org-mode]]. I am writing more and more in org mode anyway, and it's now my standard mode for writing plain text files. So here we are.

I wrote a ~Rakefile~ to contain some common steps and make conversion and maintenance simpler.

Sure, it's not exactly pretty.

If you like the old one better, it's still at https://github.com/tamouse/swaac-old-jekyll-site. It's just not being updated.
