* Link: The Worst Mistake In Computer Science
  :PROPERTIES:
  :CUSTOM_ID: link-the-worst-mistake-in-computer-science
  :END:

- published date: 2015-09-02 10:07
- keywords: ["null", "programming"]
- source: https://www.lucidchart.com/techblog/2015/08/31/the-worst-mistake-of-computer-science/

Using Ruby on Rails, I am constantly frustrated by things which might be nil, and having to construct such awful sequences as:

#+BEGIN_SRC ruby
    @order.try(:user).try(:name) || "anonymous"
#+END_SRC

Here's an article explaning the origin of the debacle.

- [[https://www.lucidchart.com/techblog/2015/08/31/the-worst-mistake-of-computer-science/][The worst mistake of computer science - Lucidchart]]

#+BEGIN_HTML
  <blockquote>
#+END_HTML

I call it my billion-dollar mistake...At that time, I was designing the first comprehensive type system for references in an object-oriented language. My goal was to ensure that all use of references should be absolutely safe, with checking performed automatically by the compiler. But I couldn't resist the temptation to put in a null reference, simply because it was so easy to implement. This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years.

#+BEGIN_HTML
  <footer>
#+END_HTML

Tony Hoare, inventor of ALGOL W.

#+BEGIN_HTML
  </footer>
#+END_HTML

#+BEGIN_HTML
  </blockquote>
#+END_HTML
