* The X-Y Problem
  :PROPERTIES:
  :CUSTOM_ID: the-x-y-problem
  :END:

- published date: 2015-04-29 08:53
- keywords: ["asking", "getting-unstuck", "how-to-ask", "learning", "questions"]
- source: [[http://mywiki.wooledge.org/XyProblem]]

Today's post is borrowed from [[http://mywiki.wooledge.org/XyProblem][Greg's Wiki]] and represents a very common problem encountered in inhabiting spaces for helping people with problems and getting help yourself.

#+BEGIN_QUOTE
  The X-Y Problem, as it is sometimes called, is a mental block which leads to enormous amounts of wasted time and energy, both on the part of people asking for help, and on the part of those providing help. It often goes something like this:
#+END_QUOTE

#+BEGIN_QUOTE

  - User wants to do X.
  - User doesn't know how to do X, but thinks they can fumble their way to a solution if they can just manage to do Y.
  - User doesn't know how to do Y either.
  - User asks for help with Y.
  - Others try to help user with Y, but are confused because Y seems like a strange problem to want to solve.
#+END_QUOTE

#+BEGIN_QUOTE
  After much interaction and wasted time, it finally becomes clear that the user really wants help with X, and that Y wasn't even a suitable solution for X.
#+END_QUOTE

#+BEGIN_QUOTE
  The problem occurs when people get their train of thought stuck on one approach and become unable to take a step back. Remaining open to having a new look at the bigger picture, these people might find their way back to X and continue searching for alternative solutions.
#+END_QUOTE

This X-Y problem is a bit of cognitive snafu that happens to everyone when trying to track down a problem. There's even a familiar phrase that was popular among organization and process improvement folks in the 80s and 90s: "When you're up to your ass in aligators, it's hard to remember the job was to drain the swamp."

Greg's [[http://mywiki.wooledge.org/XyProblem][page]] shows some really great examples of this sort of thing as it seems to happen a lot in IRC chat rooms.

To get unstuck can be hard, but remember when you find yourself deep down into the 3rd or 5th [[http://catb.org/jargon/html/Y/yak-shaving.html][yak at the barbershop]], ask yourself: "What am I trying to accomplish?" or "What's the purpose of doing this?", or to the 5-why thing by asking "Why am I doing this?" five times.

[[http://www.perlmonks.org][Perlmonks]] also has a whole [[http://www.perlmonks.org/?node=XY+Problem][batch of examples]].
