* Red Burns' List
  :PROPERTIES:
  :CUSTOM_ID: red-burns-list
  :END:

- published date: 2013-09-07 11:37
- keywords: ["red-burns", "swaac", "usability"]
- source:
- redirect_from: ["/blog/2013/09/07/red-burns-list/"]

Red Burns was the founder of the Interactive Telecommunications Program at New York University, and the mostly unknown source for nearly all things related to the design process in technology, one of the very few people who put people as the center of the design process in technology.

Following are her opening remarks to new students.

* From Red Burns' Opening Remarks to New Students
  :PROPERTIES:
  :CUSTOM_ID: from-red-burns-opening-remarks-to-new-students
  :END:

** What I want you to know:
   :PROPERTIES:
   :CUSTOM_ID: what-i-want-you-to-know
   :END:

That there is a difference between the mundane and the inspired.

That the biggest danger is not ignorance, but the illusion of knowledge.

That any human organization must inevitably juggle internal contradictions -- the imperatives of efficiency and the countervailing human trade-offs.

That the inherent preferences in organizations are efficiency, clarity, certainty, and perfection.

That human beings are ambiguous, uncertain, and imperfect.

That how you balance and integrate these contradictory characteristics is difficult.

That imagination, not calculation, is the "difference" that makes the difference.

That there is constant juggling between the inherent contradictions of a management imperative of efficiency and the human reality of ambiguity and uncertainty.

That you are a new kind of professional -- comfortable with analytical and creative modes of learning.

That there is a knowledge shift from static knowledge to a dynamic searching paradigm.

That creativity is not the game preserve of artists, but an intrinsic feature of all human activity.

That in any creative endeavor you will be discomfited and that is part of learning.

That there is a difference between long term success and short term flash.

That there is a complex connection between social and technological trends. It is virtually impossible to unravel except by hindsight.

That you ask yourself what you want and then you work backwards.

In order to problem solve and observe, you ought to know how to: analyze, probe, question, hypothesize, synthesize, select, measure, communicate, imagine, initiate, reason, create.

That organizations are really systems of cooperative activities and their coordination requires something intangible and personal that is largely a matter of relationships.

** What I hope for you:
   :PROPERTIES:
   :CUSTOM_ID: what-i-hope-for-you
   :END:

That you combine that edgy mixture of self-confidence and doubt.

That you have enough self-confidence to try new things.

That you have enough self doubt to question.

That you think of technology as a verb, not a noun; it is subtle but important difference.

That you remember the issues are usually not technical.

That you create opportunities to improvise.

That you provoke it. That you expect it.

That you make visible what, without you, might never have been seen.

That you communicate emotion.

That you create images that might take a writer ten pages to write.

That you observe, imagine and create.

That you look for the question, not the solution.

That you are not seduced by speed and power.

That you don't see the world as a market, but rather a place that people live in -- you are designing for people, not machines.

That you have a stake in magic and mystery and art.

That sometimes we fall back on Rousseau and separate mind from body.

That you understand the value of pictures, words, and critical thinking.

That poetry drives you, not hardware.

That you are willing to risk, make mistakes, and learn from failure.

That you develop a practice founded in critical reflection.

That you build a bridge between theory and practice.

That you embrace the unexpected.

That you value serendipity.

That you reinvent and re-imagine.

That you listen. That you ask questions. That you speculate and experiment.

That you play. That you are spontaneous. That you collaborate.

That you welcome students from other parts of the world and understand we don't live in a monolithic world.

That each day is magic for you.

That you turn your thinking upside down.

That you make whole pieces out of disparate parts.

That you find what makes the difference.

That your curiosity knows no bounds.

That you understand what looks easy is hard.

That you imagine and re-imagine.

That you develop a moral compass.

That you welcome loners, cellists, and poets.

That you are flexible. That you are open.

That you can laugh at yourself. That you are kind.

That you consider why natural phenomena seduce us.

That you engage and have a wonderful time.

That this will be two years for you to expand -- take advantage of it.

--------------

What impresses me most about her list -- and it is an inspired list indeed -- is that it pertains to so /much/ more than just technological design.

Threaded through the entire list is not so much how you make a *thing*, /per se/, but how you organize people, inspire people, free people to *design* such a thing. Many people regard the management of creative types, such as software engineers, user interface designers, and so on, as "The herding of cats". The comical image produced of course is that cats won't be "herded" -- they all have their own quirks and personalities, in addition to the instinct to have their own territory and be alone.

The tragedy is that managers continue to attempt to do this. The herding of programmers, the herding of designers, forcing them into some form of lock-step, predictable, and machinistic behaviour in order to produce products on a scheduled basis. "But this is a /business/" goes the argument. The reply is often "okay, okay", further grumbling and the result is a mediocre product that falls short of the founders' vision and desire.

The fundamental principle is that /people/ are doing this work to enable /other people/ to do something. Inspire the creators to inspire the customers and users. It is based entirely on uncertainty, absolutely, but boxing in the creators does not increase certainty of success of capturing and keeping customers and users, only that a certain set of features will be delivered on a certain date, while retaining the complete uncertainty of acceptability and quality.

Red Burns is speaking to all of us, not just her students in design. Good design can save the world -- but not just good design of markings, implements, and utensils -- good design of organizations that serve the constituents, stake-holders, and recipients.
