* Nginx takes the slippery road away from open source
  :PROPERTIES:
  :CUSTOM_ID: nginx-takes-the-slippery-road-away-from-open-source
  :END:

- published date: 2013-08-31 06:59
- keywords: ["nginx", "opensource", "swaac"]
- source: http://www.infoworld.com/print/225473

Clipped on 2013-08-31 06:59:24 -0500

#+BEGIN_HTML
  <!--more-->
#+END_HTML

#+BEGIN_QUOTE
  Published on /InfoWorld/ ([[http://www.infoworld.com]])

  * Nginx takes the slippery road away from open source
    :PROPERTIES:
    :CUSTOM_ID: nginx-takes-the-slippery-road-away-from-open-source-1
    :CLASS: print-title
    :END:

  By Simon Phipps

  Created /2013-08-23 05:43AM/

  Riding the wave of its broad adoption, the eponymous company behind the [[http://www.infoworld.com/t/application-servers/nginx-overtakes-microsoft-no-2-web-server-183079][open source Nginx Web server]] [1] took a turn to the proprietary this week and [[http://news.techworld.com/applications/3465208/nginx-web-server-goes-commercial-with-new-release/][announced a paid-only edition called Nginx plus]] [2]. Nginx is popular as a simpler, high-performance server and is often used as a proxy load balancing other server software, as well as for embedded use.

  The company had previously relied for revenue on large-scale and embedded deployers looking for expert skills, but this move signals a switch to an "open core" model. The move provoked widespread dismay in the free and open source software communities; Apache HTTPD veteran and Apache board member [[https://twitter.com/jimjag/status/370617704828637184][Jim Jagielski's comment]] [3] deducing the proprietary is now the most important codebase for the company was one of the milder examples.

  Of course, others couldn't understand that reaction; one voice [[https://twitter.com/patio11/status/370705322182078465][said]] [7], "Nginx offers premium support to companies it is making millions for, gets hit w/ fountain of nerdrage because they're somehow less free now." But the switch to open core definitely diminishes the commercial value of open source software; "freedom" is not just conceptual. By withholding the flexibility to use for any purpose, study the source, adapt the software, and pass to anyone without permission, Nginx has paradoxically lowered its value.

  *Why open core is worth less* Consider the general case. When any business uses this model, they have an open source "community edition" of their software product, which lacks many features of the commercial versions. It is indeed freely available under an open source license and fully functional. There will be many happy deployers of this version. If this was the only version available, there would be no issues.

  The proprietary versions are significantly different from the community version, perhaps with both the user interface and the functions. While paid licensees are often entitled to source access to this version, the proprietary licence is not perpetual -- if the customer ends their relationship with the vendor, they lose the right to use this version.

  Since this version significantly differs from the community version, there is no fallback plan, and while the customer may have access to their data (if the vendor is sufficiently enlightened about open data), there's no software they can continue to use. They are unable to trade time for money, to use Mårten Mickos' famous explanation -- they are locked in, and the open source core of the proprietary version delivers no freedom to them.

  If this latter situation was described as "proprietary" (or avoided association with open source, as for example IBM's WebSphere does in its embedding of Apache HTTPD) there would be no practical issues either. If it's clear you're surrendering your flexibility in return for convenience, that's your choice.

  The fact is, the community edition and the commercial editions have disjointed user bases. The community edition is used by a group of people who have the time and skills to deploy by themselves and who have no need of the many differences of the commercial versions. The commercial versions are feature-rich and effectively lock their users into a traditional commercial ISV relationship with the vendor. If these two were kept distinct, there would probably be no pragmatic issue. (Naturally, free-software advocates would still protest the existence of closed code, but that's not a part of this particular argument.)

  But a vendor that mixes these two encourages exactly the market confusion that OSI was designed to minimize. If they claim to be an open source business and use the presence of the community edition as a credential to sell the proprietary versions, they wrap themselves in the open source flag and their actions are exactly the gaming of the maturity of open source that I believe should be challenged.

  Will Nginx try to wrap itself in the reputation of its previous good open source citizenry while encouraging its customers to do without the flexibility of open source? Time will tell, but I strongly encourage the company to avoid this trap.

  /This article, "[[http://www.infoworld.com/d/open-source-software/nginx-takes-the-slippery-road-away-open-source-225473?source=footer][Nginx takes the slippery road away from open source]] [8]," was originally published at [[http://www.infoworld.com/?source=footer][InfoWorld.com]] [9]. Read more of the [[http://www.infoworld.com/blogs/open-sources?source=footer][Open Sources blog]] [10] and follow the latest developments in [[http://www.infoworld.com/d/open-source-software?source=footer][open source]] [11] at InfoWorld.com. For the latest business technology news, follow [[http://twitter.com/infoworld][InfoWorld.com on Twitter]] [12]./

  - [[/category/channels/open-source-software][Open Source Software]]
  - [[/t/application-servers][Application Servers]]
  - [[/t/open-source-software][Open Source Software]]

  --------------

  *Source URL (retrieved on /2013-08-31 04:58AM/):* [[http://www.infoworld.com/d/open-source-software/nginx-takes-the-slippery-road-away-open-source-225473]]

  *Links:* [1] http://www.infoworld.com/t/application-servers/nginx-overtakes-microsoft-no-2-web-server-183079\\
  [2] http://news.techworld.com/applications/3465208/nginx-web-server-goes-commercial-with-new-release/\\
  [3] https://twitter.com/jimjag/status/370617704828637184\\
  [4] http://www.infoworld.com/t/application-servers/nginx-overtakes-microsoft-no-2-web-server-183079?source=fssr\\
  [5] http://www.infoworld.com/newsletters/subscribe?showlist=infoworld_techbrief&source=ifwelg_fssr\\
  [6] http://www.infoworld.com/newsletters/subscribe?showlist=infoworld_open_source&source=ifwelg_fssr\\
  [7] https://twitter.com/patio11/status/370705322182078465\\
  [8] http://www.infoworld.com/d/open-source-software/nginx-takes-the-slippery-road-away-open-source-225473?source=footer\\
  [9] http://www.infoworld.com/?source=footer\\
  [10] http://www.infoworld.com/blogs/open-sources?source=footer\\
  [11] http://www.infoworld.com/d/open-source-software?source=footer\\
  [12] http://twitter.com/infoworld\\
#+END_QUOTE
