* UX: What Does "Flat Design" Really Mean? (link)
  :PROPERTIES:
  :CUSTOM_ID: ux-what-does-flat-design-really-mean-link
  :END:

- published date: 2013-12-23 23:53
- keywords: ["design", "swaac", "ux", "web"]
- source:
- redirect_from: ["/blog/2013/12/23/ux-what-does-flat-design-really-mean-link/"]

In a really good article, [[https://medium.com/building-things-on-the-internet/7c697fbbe8be][/Is your interface what it needs to be?/]] on [[http://medium.com][Medium]], [[https://medium.com/@HugoMNL][Andrei Gonzales]] explains why the current "Flat Design" trend is more than just a fad, and how to look deeper into choices made for user interaction (UX) design.

#+BEGIN_QUOTE
  Interaction design trends seem to be jumping from one bandwagon to the next, but if you look closer, you'll find that there is a method behind the madness.
#+END_QUOTE

#+BEGIN_QUOTE
  If you are in any way involved with anything interactive, it would be fairly safe to say that you've heard all the talk about the current "Flat Design"" trend, and how it is a great many things. Sadly though, a lot of opinions that are being presented as facts have failed to understand and explain why this particular approach has become so pervasive in modern user interfaces.
#+END_QUOTE

#+BEGIN_QUOTE
  Because of all the misinformation, some designers are convinced that "Flat" should be written off as a trend in the same way that flared jeans and flannel shirts were trends, like some User Interface flavor-of-the-month.
#+END_QUOTE

He even introduces a word I had never heard of before: [[http://en.wikipedia.org/wiki/Skeuomorph][*Skeuomorphism*]]:

#+BEGIN_QUOTE
  To describe it briefly: it's a way of replicating certain elements and attributes of an object (often a physical one), and then applying them to another object or medium.
#+END_QUOTE

The concept of the computer "desktop" and "windows", even "folders", are examples of this concept.

Give the article a read, it's quite good.
