* This is why Gandi.Net is my Registrar of Choice
  :PROPERTIES:
  :CUSTOM_ID: this-is-why-gandi.net-is-my-registrar-of-choice
  :END:

- published date: 2014-01-15 20:00
- keywords: ["gandi", "swaac", "web-hosting"]
- source:
- redirect_from: ["/blog/2014/01/15/this-is-why-gandi-dot-net-is-my-registrar-of-choice/"]

I have been trying to flee the [[http://www.theregister.co.uk/2011/07/12/godaddy_shuts_down_nodaddy/][Large US Internet Registrar and Hosting company]] for the past year or more. [[http://gandi.net][Gandi.Net]] has been my registrar of choice for a few years now, and I run a VPS from them as well.

My experiences with Gandi have all been pretty wonderful, unlike my experiences the [[http://www.theregister.co.uk/2011/07/12/godaddy_shuts_down_nodaddy/][LUSIR]].

This month's newsletter from Gandi gives me even more reason to cheer them, and to continue to recommend them to my friends, colleagues, and others:

#+BEGIN_QUOTE
  ##Feb 11: The Day We Fight Back Against Mass Surveillance

  Gandi has always stood up for digital due process, online privacy, and electronic freedom. We support the EFF, and have always worked to protect the Internet for free expression and open communication. As part of the Internet Infrastructure Coalition (i2coalition.com), we are actively lobbying the US Congress for reasonable reform of CFAA, the law that activist Aaron Schwartz was charged under.

  We feel it is important to speak out for your online rights, and to help our lawmakers make laws that enhance security while preserving our freedom of expression. On Feb 11, we will join Mozilla, the EFF, Fight for the Future, Gandi.net, and others in advocating for more reasonable laws to protect our rights, and the rights of activists and whistleblowers.

  See: https://thedaywefightback.org

  ##A Conference of One's Own: She's Geeky

  Fighting injustice is hard enough when you have a clear target, and things like pervasive microinequities are anything but. Sometimes, the most effective way to deal with a failing system is to build your own alternative. We applaud this spirit, and that's why we're proud to support and participate in safe, friendly spaces in IT like the Bay Area She's Geeky unConference, happening Fri-Sun, January 24-26, 2014 in Mountain View, CA.

  Gandi's delegation is excited to attend. If you see us there, be sure to say hi! We'd love to chat.

  For more information or to sponsor She's Geeky, see www.shesgeeky.org. And by the way, if you know of an event you think we'd be into, let us know at newsletter-en@gandi.net.
#+END_QUOTE

More now than before, Gandi seems to be a company that actually is capable of showing concern and care for people, and not just out to rake in money.
