* Converting blog to pure Jekyll
  :PROPERTIES:
  :CUSTOM_ID: converting-blog-to-pure-jekyll
  :END:

- published date: 2014-09-27 14:29
- keywords: ["jekyll", "swaac"]
- source:
- redirect_from: ["/blog/2014/09/27/converting-blog-to-pure-jekyll/"]

I had originally created this blog using Octopress, but have become disillusioned with the lack of progress in that, and the lack of adoption of nifty new capabilities in [[http://jekyllrb.com][Jekyll]]. So I redid it.

From creating the new jekyll site, moving the posts, converting categories and tags (which took by /far/ the longest time), it was about 4 hours. The majority of it was in place in about an hour, tops. Since OP eschewed tags for just categories, and Jekyll likes both, it was a major piece of editing time grinding through the posts (240 of them!) to get things in the right place. Happy now.

I am keeping the Jekyll-New theme, which you see here, at least until I get the gumption to do some more site design. I like it: it's clean, it's pretty, it's efficient. If I start to see a bunch of sites looking just like it, I may shift. The default OP design is so ugly to me, with it's dim, grey outlook, I had to change my design. Not so here. Go Jekyllers!!
