* Tweet by @c089: hidden costs of poor programming
  :PROPERTIES:
  :CUSTOM_ID: tweet-by-c089-hidden-costs-of-poor-programming
  :END:

- published date: 2015-12-01 07:27
- keywords: ["productivity", "programming", "twitter"]
- source: https://twitter.com/c089/status/671624868908126208

wow is this ever true:

#+BEGIN_HTML
  <blockquote class="twitter-tweet" lang="en">
#+END_HTML

#+BEGIN_HTML
  <p lang="en" dir="ltr">
#+END_HTML

well-crafted code is expensive.

good developers spending hours on fixing bad code is very, very, very, very expensive.

#+BEGIN_HTML
  </p>
#+END_HTML

--- Chris Hug (@c089) December 1, 2015

#+BEGIN_HTML
  </blockquote>
#+END_HTML

#+BEGIN_HTML
  <script async src="//platform.twitter.com/widgets.js"
  charset="utf-8"></script>
#+END_HTML

--------------

Back in the day, at the /old/ HP (not this one, the one that still was named after the founders, Bill and Dave), we talked quite a bit about "Cost of Quality" -- which was entirely directed at the costs of /poor/ quality code released into the field. The direct costs went up by one or two orders of magnitude each step along the lifecycle. The cost of fixing a bug post-release were something like 10 thousand times the cost of fixing it in development.
