* Link: Your Software Is Never Perfect
  :PROPERTIES:
  :CUSTOM_ID: link-your-software-is-never-perfect
  :END:

- published date: 2016-05-30 07:41
- keywords: ["improvement", "mindfulness", "swaac"]
- source:
- link: {"href"=>"https://www.physicsforums.com/insights/software-never-perfect/", "title"=>"Your Sofware Is Never Perfect", "date"=>"2016-05-30", "author"=>{"name"=>"D H", "url"=>"https://www.physicsforums.com/members/d-h.42688/"}}

#+BEGIN_QUOTE
  We occasionally have students ask for help on software, "My software is perfect, but it doesn't work!" Your software is never perfect. My own software is never perfect. I recently found that I made someone's top ten list with regard to software that I had written 37 years ago. It's not a top ten list anyone would aspire to be listed on. Software that I wrote in 1979 is number two on this list of ten historical software bugs with extreme consequences. I learned some very important lessons from that experience.
#+END_QUOTE

Some very important lessons for all of us. Hubris often leads to a downfall.
